### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by grgmll** [jdtsmith/homebridge-denonmarantzavr#2]
Could you add the volume control?

**Comment by jdtsmith** [comment]
I have experimented with Volume control through a Speaker accessory, but iOS home (and Siri) can't control it.  The Eve app can, but might as well open the Denon app at that point.  If you're interested in playing with it I can point you to it.

**Comment by jdtsmith** [comment]
This is implements in 0.2.0.  Home still doesn't work with Speaker services.
