### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by ghost** [jdtsmith/homebridge-denonmarantzavr#3]
Delete

**Comment by jdtsmith** [comment]
Your second looks OK at a glance.  Probably extra whitespace issues in your config.json.  Try running it through https://jsonlint.com before  giving to homebridge.

**Comment by YRRK** [comment]
Hmm seems so easy, but maybe too technical for me. If I input your example code, it's also being corrected by https://jsonlint.com So who's right, what's the true formatting?

**Comment by YRRK** [comment]
It does not seems to matter what I input in the config.json. I always get the same error when re-starting the homebridge (Running the current latest version, clean-install, raspberrypi 3B+):

    at tryModuleLoad (module.js:501:12)
    at Module.load (module.js:561:32)
    at Object.Module._extensions..js (module.js:660:10)
    at Module._compile (module.js:649:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:341:16)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:403:20)
    at AVRPlatform.accessories (/usr/local/lib/node_modules/homebridge-denonmarantzavr/src/index.js:22:22)
[2019-5-12 12:04:34] TypeError: Cannot read property 'forEach' of undefined
    at tryModuleLoad (module.js:501:12)
    at Module.load (module.js:561:32)
    at Object.Module._extensions..js (module.js:660:10)
    at Module._compile (module.js:649:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:341:16)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:403:20)
    at AVRPlatform.accessories (/usr/local/lib/node_modules/homebridge-denonmarantzavr/src/index.js:22:22)
[2019-5-12 12:04:21] TypeError: Cannot read property 'forEach' of undefined

**Comment by jdtsmith** [comment]
It's not reading your `config.zones` correctly.  Attach your config.json and I can take a look.

**Comment by jdtsmith** [comment]
BTW I presume you are wrapping your entire config.json in the appropriate `homebridge` info:

```json
{
  "bridge": {
    "name": "MyHomebridge",
    "port": 50001,
    "username": "CC:33:44:55:AA:BB",
    "pin": "999-99-99"
  },

  "description": "My HomeBridge Config",

  "platforms": ...
}
```

**Comment by YRRK** [comment]
When using the Homebrigde iOS app to configure the pi and your plug-in, the platform part of the config.json looks like below. Then I get the error. I’m gonna subsitute this code with your example code, reboot, look again. En send i to you. But for now. This is de json.

  "platforms" : [
    {
      "sensors" : false,
      "users" : {

      },
      "platform" : "Hue",
      "name" : "Phillips Hue",
      "nativeHomeKitSensors" : true,
      "lights" : true
    },
    {
      "ip" : "192.168.51.6",
      "name" : "DenAVR",
      "platform" : "DenonMarantzAVR"
    }
  ]
}


Op 12 mei 2019 om 18:23 heeft JD Smith <notifications@github.com> het volgende geschreven:

It's not reading your config.zones correctly. Attach your config.json and I can take a look.

**Comment by YRRK** [comment]
Yes, and my Homebridge works with other gadgets in the house. Except for the Denon now :)

Op 12 mei 2019 om 18:26 heeft JD Smith <notifications@github.com> het volgende geschreven:

BTW I presume you are wrapping your entire config.json in the appropriate homebridge info:

{
  "bridge": {
    "name": "MyHomebridge",
    "port": 50001,
    "username": "CC:33:44:55:AA:BB",
    "pin": "999-99-99"
  },

  "description": "My HomeBridge Config",

  "platforms": ...
}

**Comment by YRRK** [comment]
Yes, and my Homebridge works with other gadgets in the house. Except for the Denon now :)

**Comment by YRRK** [comment]
Here is my complete config.json I anonimized the network data.
I tried to use your example code but it's very hard so match the original config.json because in the example the spaces and : are different. Running it trough jsonlint.com goes wrong.

[config.json.zip](https://github.com/jdtsmith/homebridge-denonmarantzavr/files/3170423/config.json.zip)

Here also in text.

{
  "accessories" : [
    {
      "name" : "50EX780",
      "ipaddress" : "192.168.bla.bla",
      "accessory" : "Panasonic-TV"
    },
    {
      "name" : "40CX700_Series",
      "ipaddress" : "192.168.bla.bla”,
      "accessory" : "Panasonic-TV"
    },
    {
      "name" : "Pi Temp",
      "accessory" : "RaspberryPiTemperature"
    },
    {
      "accessory" : "people",
      "people" : [
        {
          "name" : "phone",
          "target" : "phone"
        },
        {
          "name" : "iphone2",
          "target" : "192.168.bla.bla"
        }
      ],
      "name" : "People",
      "thershold" : ""
    }
  ],
  "bridge" : {
    "username" : "CD:22:bla:bla",
    "name" : "Homebridge",
    "pin" : "035-45-bla",
    "port" : 51bla
  },
  "platforms" : [
    {
      "sensors" : false,
      "users" : {

      },
      "platform" : "Hue",
      "name" : "Phillips Hue",
      "nativeHomeKitSensors" : true,
      "lights" : true
    },
    {
      "platform": "DenonMarantzAVR",
      "avrs": [
        {
          "name": "DenAVR",
          "ip": "192.168.51.6",
          "model": "DenonDN-500AV",
          "zones": 2,
          "zonenames": [
            "Woonkamer",
            "Zone2"
          ]
    }
  ]
}

**Comment by jdtsmith** [comment]
"ipaddress" : "192.168.bla.bla”,

This has a special “curly” double-quote mark at the end

**Comment by YRRK** [comment]
Hi jdtsmith,

Oke sorry, don't mention the bla”. That happenede because I scrambled the code. It's not what I actually used. Here below is the code again, without the error.
So I tried to construct this code with your example, homebridge won't start with it. I get that "TypeError: Cannot read property 'forEach' of undefined
at tryModuleLoad (module.js:501:12) etc. error.
Could you please help me with the correct layout? JSONLint makes things worse. Could it be the : or the [  { 's?


  },
  "platforms" : [
    {
      "sensors" : false,
      "users" : {
        "001688FFFDF6FG5D" : "uBAzcj1xwaqKr21VNHiaBA0u3i0QMXpTBXs1CVFY"
      },
      "platform" : "Hue",
      "name" : "Phillips Hue",
      "nativeHomeKitSensors" : true,
      "lights" : true
     },
     {
       "platform": "DenonMarantzAVR",
       "avrs": [
         {
           "name": "DenAVR",
           "ip": "192.168.51.6",
           "model": "DenonDN-500AV",
           "zones": 2,
           "zonenames": [
             "Woonkamer",
             "Zone2"
           ]
    }
  ]
}

**Comment by YRRK** [comment]
[config.json.zip](https://github.com/jdtsmith/homebridge-denonmarantzavr/files/3174508/config.json.zip)
