### ISSUE TITLE
throttledQueue too low throws warning

### ISSUE THREAD

**Issue by Jafalex** [jdtsmith/homebridge-denonmarantzavr#5]
Hi there,

In `AVRAccessory.js`, `throttledQueue` passes params `1` and `150`. I therefore always get the following warning message from the throttled-queue code.

> An interval of less than 200ms can create performance issues.

Is there any harm in changing to `1` and `200`?

Thanks!

**Comment by jdtsmith** [comment]
No harm. Implements in 0.2.0.
