### ISSUE TITLE
More functions and buttons via config.json? Possible?

### ISSUE THREAD

**Issue by houser42** [jdtsmith/homebridge-denonmarantzavr#7]
Hello,

Got this working with just power on/off on my Marantz receiver. Great!
Is there a way to add more functions via the config.json file already?
I am pretty deep into Home theatre programming so have all the codes for this in some other
remote formats.
Setting input and a fixed volume are the obvious ones I suppose.
Let us know if you have a sec? Many thanks..

**Comment by jdtsmith** [comment]
Right now I'm considering adding it as a new homekit "television" so that volume, input selection and power can work through one HomeKit service.  Are you able to work from a plugin source branch?

**Comment by houser42** [comment]
By plugin source branch, you mean can I compile libs myself?
If that is what you mean, sure with some half-decent docs probably. 
Happy to hear you are working on this.

**Comment by jdtsmith** [comment]
Yeah, it's pretty simple.  You can clone the repository with git, then switch to the development branch, then call homebridge with `-U` to tell it to look at that directory for plugins.  Will report back if and when I have something worth trying out.

**Comment by houser42** [comment]
I look forward to that git!
Meanwhile, is there any chance of building single commands or simple macros with the existing plugin by editing conf files or in the json.config?
Example: power on/ set input/ set volume
That sort of thing. If you have a sec?

**Comment by jdtsmith** [comment]
Right now it’s just power for all configured zones.  Looking into inputs and volume with auto-discovery.

**Comment by houser42** [comment]
Alright, perfect. Keep us posted when you get the chance. Many thanks!

**Comment by houser42** [comment]
Hi @jdtsmith Just a follow up question if you have a sec?
When you wrote: "new homekit television", does that mean there is a possibility for a swipe remote similar to the one there is in there for Apple TV? Is that possible? Just very curious?

**Comment by jdtsmith** [comment]
Yes!  See, e.g. [this plugin](https://github.com/tavicu/homebridge-samsung-tizen/issues/88).  Haven't made progress on the new plugin architecture unfortunately.

**Comment by houser42** [comment]
Thanks for the comment @jdtsmith . Appreciated. That is indeed very promising and encouraging , regardless of the timing of it all. That would really be very useful if it can be done! Thanks again.

**Comment by houser42** [comment]
Hello @jdtsmith 
FWIW, [this plugin](https://www.npmjs.com/package/homebridge-kodi) also does the job that I just got working for Kodi, so I now know a little bit about what the functionality looks like presently. It comes up as a second menu based remote choice in Control Center, rather than in Hue app.  
No swipe, just buttons. Little baby steps..but useful..  FWIW.

**Comment by TarakAmmous** [comment]
Any news about the homekit integration?
